name: gopeed
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.8.3+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  styled_widget: ^0.4.0+3
  context_menus: ^1.2.0
  json_annotation: ^4.8.1
  dio: ^5.2.1
  path_provider: ^2.1.4
  file_picker: ^8.1.2
  rounded_loading_button_plus: ^3.0.1
  url_launcher: ^6.3.1
  logger: ^1.4.0
  desktop_drop: ^0.4.4
  package_info_plus: ^8.1.0
  fluent_ui: ^4.9.2
  path: ^1.9.0
  badges: ^3.0.3
  app_links: ^6.3.3
  uri_to_file: ^1.0.0
  window_manager: ^0.4.2
  hotkey_manager: ^0.2.3
  share_plus: ^10.1.0

  # FIX (intl 0.20.2 pinned by flutter_localizations)
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.0.0

  flutter_foreground_task: ^8.2.0
  open_filex: ^4.7.0
  tray_manager:
    git:
      url: https://github.com/monkeyWie/tray_manager.git
      ref: main
      path: packages/tray_manager
  lecle_downloads_path_provider: ^0.0.2+8
  hive: ^2.2.3
  launch_at_startup: ^0.3.1
  args: ^2.5.0
  toggle_switch: ^2.3.0
  permission_handler: ^11.3.1
  device_info_plus: ^11.1.0
  checkable_treeview: ^1.3.1
  contextmenu_plus: ^1.0.1
  contentsize_tabbarview: ^0.0.2
  win32_registry: ^1.1.5
  share_handler: ^0.0.22
  crypto: ^3.0.6
  open_dir: ^0.0.2+1
  webview_flutter: ^4.10.0
  install_plugin:
    git:
      url: https://github.com/hui-z/flutter_install_plugin.git
      ref: cf08af829f4a4145634f8a047108f505fdbe5eaa
  flutter_svg: ^2.0.17
  dart_ipc: ^1.0.1

dependency_overrides:
  # Ensure compatibility with flutter_localizations pin
  intl: 0.20.2

  permission_handler_windows:
    git:
      url: https://github.com/monkeyWie/flutter-permission-handler.git
      ref: 35fc72c30262b9b49e1965b48a7524b44ba9daa7
      path: permission_handler_windows

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  ffigen: ^8.0.2
  # build json model: dart run build_runner build --delete-conflicting-outputs
  build_runner: ^2.2.1
  json_serializable: ^6.3.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/tray_icon/
    - assets/extension/
    - assets/icon/
    - assets/branding/
    # Browser extension native host binary, see https://github.com/GopeedLab/gopeed/tree/main/cmd/host
    - assets/exec/

  fonts:
    - family: Gopeed
      fonts:
        - asset: assets/fonts/Gopeed.ttf

# dart run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/icon/icon_1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon_1024.png"
  windows:
    generate: true
    image_path: "assets/icon/icon_1024.png"
  macos:
    generate: true
    image_path: "assets/icon/icon_macos_1024.png"

# dart run ffigen
ffigen:
  name: LibgopeedBind
  description: Bindings to gopeed library.
  output: "lib/core/ffi/libgopeed_bind.dart"
  headers:
    entry-points:
      - "include/libgopeed.h"
